# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableSelectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tableSelectLabel.setObjectName("tableSelectLabel")
        self.horizontalLayout_3.addWidget(self.tableSelectLabel)
        self.tableSelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tableSelect.setObjectName("tableSelect")
        self.horizontalLayout_3.addWidget(self.tableSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.filterLabel.setObjectName("filterLabel")
        self.horizontalLayout.addWidget(self.filterLabel)
        self.filterInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.filterInput.setObjectName("filterInput")
        self.horizontalLayout.addWidget(self.filterInput)
        self.sortLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sortLabel.setObjectName("sortLabel")
        self.horizontalLayout.addWidget(self.sortLabel)
        self.sortBySelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.sortBySelect.setObjectName("sortBySelect")
        self.horizontalLayout.addWidget(self.sortBySelect)
        self.sortOrderSelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.sortOrderSelect.setObjectName("sortOrderSelect")
        self.horizontalLayout.addWidget(self.sortOrderSelect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.tableView.setColumnCount(0)
        self.tableView.setRowCount(0)
        self.verticalLayout.addWidget(self.tableView)
        self.sqlView = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.sqlView.setObjectName("sqlView")
        self.verticalLayout.addWidget(self.sqlView)
        self.errorsView = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.errorsView.setReadOnly(True)
        self.errorsView.setObjectName("errorsView")
        self.verticalLayout.addWidget(self.errorsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableSelectLabel.setText(_translate("MainWindow", "Table"))
        self.filterLabel.setText(_translate("MainWindow", "Filter"))
        self.sortLabel.setText(_translate("MainWindow", "Sort"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
